In [4]:
import tensorflow_text as text
import tensorflow_hub as hub

In [5]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [7]:
preprocessing_model_bert = hub.KerasLayer(preprocess_url)

In [8]:
test_text = ["I love Python Programming.", "NLP is one of my favorite subjects."]
text_preprocessing = preprocessing_model_bert(test_text)
text_preprocessing.keys()

dict_keys(['input_type_ids', 'input_word_ids', 'input_mask'])

In [9]:
text_preprocessing["input_mask"]

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [10]:
text_preprocessing["input_word_ids"]

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  1045,  2293, 18750,  4730,  1012,   102,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [11]:
text_preprocessing["input_type_ids"]

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [12]:
bert_model = hub.KerasLayer(encoder_url)

In [14]:
bert_results = bert_model(text_preprocessing)

In [15]:
bert_results.keys()

dict_keys(['pooled_output', 'sequence_output', 'default', 'encoder_outputs'])

In [16]:
bert_results["pooled_output"]

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.8951971 , -0.5652015 , -0.9635777 , ..., -0.91343504,
        -0.7490767 ,  0.9060876 ],
       [-0.89997613, -0.45204493, -0.81001514, ..., -0.7583173 ,
        -0.66137713,  0.9174448 ]], dtype=float32)>

In [17]:
bert_results["sequence_output"]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[-0.14807934,  0.07996579, -0.22093096, ..., -0.20253035,
          0.2576961 ,  0.7049945 ],
        [ 0.5830308 ,  0.07326362, -0.4499312 , ...,  0.01308995,
          0.48147476,  0.5803143 ],
        [ 1.0260481 ,  1.1624296 ,  0.3688557 , ...,  0.07882808,
          0.41806513,  0.49768522],
        ...,
        [ 0.22242631,  0.05824689,  0.61200786, ...,  0.21087879,
         -0.22103421,  0.0076685 ],
        [ 0.15885477,  0.12060905,  0.5830297 , ...,  0.12881607,
         -0.22729343,  0.06657913],
        [ 0.1505453 ,  0.04488018,  0.42874846, ...,  0.13534114,
         -0.21440805,  0.08028127]],

       [[ 0.0299046 ,  0.09619474, -0.37175518, ..., -0.09123426,
          0.19556138,  0.62186116],
        [ 0.5668323 , -1.0436115 , -0.27858996, ..., -0.31101227,
          0.6261699 ,  0.6019602 ],
        [-0.26659605, -0.44158968, -0.5640639 , ..., -0.5152797 ,
         -0.47222972, -0.23826551],
        ...,

In [18]:
bert_results["encoder_outputs"]

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 7.68575892e-02,  8.55229199e-02, -1.43926919e-01, ...,
           2.18434513e-01, -3.42592597e-04, -1.00857109e-01],
         [ 5.54973602e-01,  8.12005043e-01, -8.03655237e-02, ...,
           6.21268511e-01,  7.78178751e-01,  1.55911684e-01],
         [ 1.38049138e+00,  5.13571560e-01,  4.02852565e-01, ...,
           4.52889144e-01,  6.42696142e-01,  1.05071418e-01],
         ...,
         [ 1.17637455e-01, -2.08516657e-01,  6.96695387e-01, ...,
          -9.03740078e-02, -1.49849504e-01,  2.53298461e-01],
         [ 1.67994350e-02, -2.29621977e-01,  5.36866248e-01, ...,
          -4.17865850e-02, -4.65779342e-02,  1.50048301e-01],
         [ 1.56628922e-01, -1.45577177e-01,  6.00848675e-01, ...,
           3.55005264e-01, -3.76604497e-01,  5.87032810e-02]],
 
        [[-9.58251208e-03,  5.21982238e-02, -1.41820937e-01, ...,
           2.41770923e-01, -7.62006044e-02, -9.73424911e-02],
         [ 5.48773766e-01, -7.9

In [19]:
len(bert_results["encoder_outputs"])

12

In [20]:
bert_results["encoder_outputs"][-1] == bert_results["sequence_output"]

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>