In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [ ]:
reviews = ["nice food",
        "amazing restaurant",
        "too good",
        "just loved it!",
        "will go again",
        "horrible food",
        "never go there",
        "poor service",
        "poor quality",
        "needs improvement"]

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [ ]:
one_hot("amazing restaurant",30)

[3, 29]

In [ ]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[11, 24], [3, 29], [15, 5], [27, 25, 4], [20, 14, 2], [27, 24], [29, 14, 4], [23, 29], [23, 22], [18, 2]]


In [ ]:
max_length = 5
padded_reviews = pad_sequences(encoded_reviews, maxlen = max_length, padding = "post")
print(padded_reviews)

[[11 24  0  0  0]
 [ 3 29  0  0  0]
 [15  5  0  0  0]
 [27 25  4  0  0]
 [20 14  2  0  0]
 [27 24  0  0  0]
 [29 14  4  0  0]
 [23 29  0  0  0]
 [23 22  0  0  0]
 [18  2  0  0  0]]


In [ ]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length = max_length, name = "embedding"))
model.add(Flatten())
model.add(Dense(1, activation = "sigmoid"))

In [ ]:
X = padded_reviews
y = sentiment

In [ ]:
model.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 5)              150       
                                                                 
 flatten (Flatten)           (None, 25)                0         
                                                                 
 dense (Dense)               (None, 1)                 26        
                                                                 
Total params: 176
Trainable params: 176
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.fit(X, y, epochs = 50)

Epoch 1/50
1/1 [==============================] - 0s 13ms/step - loss: 0.6519 - accuracy: 1.0000
Epoch 2/50
1/1 [==============================] - 0s 12ms/step - loss: 0.6508 - accuracy: 1.0000
Epoch 3/50
1/1 [==============================] - 0s 12ms/step - loss: 0.6497 - accuracy: 1.0000
Epoch 4/50
1/1 [==============================] - 0s 10ms/step - loss: 0.6486 - accuracy: 1.0000
Epoch 5/50
1/1 [==============================] - 0s 10ms/step - loss: 0.6475 - accuracy: 1.0000
Epoch 6/50
1/1 [==============================] - 0s 12ms/step - loss: 0.6464 - accuracy: 1.0000
Epoch 7/50
1/1 [==============================] - 0s 11ms/step - loss: 0.6453 - accuracy: 1.0000
Epoch 8/50
1/1 [==============================] - 0s 11ms/step - loss: 0.6441 - accuracy: 1.0000
Epoch 9/50
1/1 [==============================] - 0s 12ms/step - loss: 0.6430 - accuracy: 1.0000
Epoch 10/50
1/1 [==============================] - 0s 10ms/step - loss: 0.6418 - accuracy: 1.0000
Epoch 11/50
1/1 [============

In [ ]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 160ms/step - loss: 0.5855 - accuracy: 1.0000


1.0

In [ ]:
weights = model.get_layer("embedding").get_weights()[0]
len(weights)

30

In [ ]:
weights[15]

array([ 0.05677385, -0.11286373, -0.08188833,  0.15380092, -0.10484307],
      dtype=float32)

In [ ]:
weights[25]

array([-0.10990778,  0.10174755,  0.09185839,  0.12322415, -0.15218522],
      dtype=float32)

In [ ]:
weights[10]

array([-0.02358039,  0.03139243, -0.04007475, -0.009316  , -0.041779  ],
      dtype=float32)